micronaut:
  security:
    enabled: true
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://openldap:389'
          managerDn: 'cn=admin,dc=example,dc=in'
          managerPassword: 'password'
        search:
          base: "ou=User,dc=example,dc=in"
          filter: "(uid={0})"
        groups:
          enabled: false

akhq:
  connections:
    local:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
        - name: "connect"
          url: "http://connect:8083"
      ksqldb:
        - name: "ksqldb"
          url: "http://ksqldb:8088"